name: test
on: [ push, pull_request ]
permissions:
  contents: read
jobs:
  test:
    name: Test ${{ matrix.target }} on macos-latest
    matrix:
      target: [ "npm", "yarn","yarn-berry", "pnpm" ]
    # zsh is pre-installed on macos-latest
    # https://github.com/actions/runner-images/issues/264
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Enable corepack
        run: corepack enable
      - name: Test
        shell: zsh {0}
        run: |
          set -e
          # enable compinit before loading
          autoload -Uz compinit && compinit
          # load ni.zsh
          source ./ni.zsh
          # move to test dir
          cd test/${{ matrix.target }}
          # Install dependencies
          ni
          # run tests
          ni test
          # run scripts
          ni run main
          # exec envinfo
          ni exec envinfo
          # add new dependencies
          ni add lodash
          # remove dependencies
          ni remove lodash
