name: test
on: [ push, pull_request ]
permissions:
  contents: read
jobs:
  test:
    name: Test on macos-latest
    # zsh is pre-installed on macos-latest
    # https://github.com/actions/runner-images/issues/264
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        shell: zsh {0}
        run: |
          set -ex
          source ./ni.zsh
          # move to test/example
          cd test/example
          # Install dependencies
          ni
          # run tests
          ni test
          # run scripts
          ni run main
          # exec envinfo
          ni exec envinfo
          # add new dependencies
          ni add lodash
          # remove dependencies
          ni remove lodash
